### PR TITLE
Add more Markdown support: list completion, indent, shortcuts, etc.

### PR DESCRIPTION
**Pull request by hand-dot**
Hi @r7kamura 

Thank you for creating this chrome extension.
I wanna use like [vscode-markdown ](https://github.com/yzhang-gh/vscode-markdown ). so, I added [monaco-markdown](https://www.npmjs.com/package/monaco-markdown). If you like this, please merge.

CleanShot20220721at183053

( I forgot to turn off Grammarly. Please ignore the Grammarly icon.)

### CODE REVIEW

**Comment by r7kamura** [comment]
Great! I wanted this list syntax feature too. I'll see it soon.

**Comment by hand-dot** [comment]
Thanks✌️

**Comment by r7kamura** [comment]
OK, it looks good. I'll merge this and send a new release to chrome web store 👍 

I read through the source code of [monaco-markdown](https://github.com/traff/monaco-markdown), and tried this branch on my local environment. It works well, the list syntax support feels good. I also ensured that it doesn't harm those who do not use Markdown.

A few shortcut keys would be added, but well, it would not be a problem and would be useful for Markdown users. Some of them won't work, though, because the browser's shortcut keys will take precedence.

image

I think the formatting supprot for the table syntax might be quite useful for some users 😃 
(Press <kbd>F1</kbd> to show command pallet then search by "format", or <kbd>Shift+Alt+B</kbd> on Windows)

**Comment by r7kamura** [comment]
Released v0.2.0 on GitHub, and submitted this to Chrome Web Store 🎉 
https://github.com/r7kamura/editabro/releases/tag/v0.2.0

Hopefully it will be published in the next few days.

**Comment by r7kamura** [comment]
The new version has been released on Chrome Web Store today, so probably it's already updated automatically and ready to use! Thank you for your contribution 👍

**Pull request merged**
